import Head from 'next/head'
import Link from 'next/link'
import type {} from 'redux-thunk/extend-redux';
import styles from '../src/styles/Home.module.scss'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4>
          This is Home Page.
        </h4>

        <h3 className={styles.description}>
          <Link 
            href='/video-list'>
            Go to Video List
          </Link>
        </h3>
      </main>

    </div>
  )
}

export default Home
