import Head from 'next/head'
import Link from 'next/link'
import type {} from 'redux-thunk/extend-redux';

import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Home Page
        </h1>

        <p className={styles.description}>
          links:
          <Link 
            href='/blog'>
            Video List
          </Link>
        </p>
      </main>

    </div>
  )
}

export default Home
